import type { DB, Venue } from "./types";

const v = (p: Omit<Venue, "stats" | "lastPostedAt">): Venue => ({ ...p, stats: { posts: 0, offers: 0, accepted: 0 } });

export function seed(): DB {
  const now = new Date().toISOString();
  return {
    goalUsd: 100_000,
    currentItemId: "item_paperclip",
    items: [
      {
        id: "item_paperclip",
        name: "One red paperclip",
        description: "A single, slightly bent, red-coated steel paperclip. Where it all begins.",
        category: "misc",
        estValueUsd: 0.01,
        valueLow: 0.005,
        valueHigh: 0.05,
        valuationNotes: "Bulk paperclips retail ~$2 per 500.",
        acquiredAt: now,
      },
    ],
    venues: [
      v({
        id: "x_main",
        channel: "x",
        name: "X / Twitter (own account)",
        target: "timeline",
        categories: ["*"],
        minValueUsd: 0,
        maxValueUsd: 1e9,
        cooldownHours: 6,
        permission: "not_required",
        formatHint: "Max 270 chars. Punchy, emoji-light, always link the live log. Account bio must say it is an automated AI agent.",
      }),
      v({
        id: "reddit_barter",
        channel: "reddit",
        name: "r/Barter",
        target: "Barter",
        categories: ["*"],
        minValueUsd: 0,
        maxValueUsd: 5000,
        cooldownHours: 168,
        permission: "pending",
        formatHint: "Title format: [H] <item> [W] <what you want> [LOC] <country>. Body: condition, photos link, disclose AI agent, link log.",
      }),
      v({
        id: "reddit_hardwareswap",
        channel: "reddit",
        name: "r/hardwareswap",
        target: "hardwareswap",
        categories: ["electronics", "computers", "gaming"],
        minValueUsd: 50,
        maxValueUsd: 5000,
        cooldownHours: 168,
        permission: "pending",
        formatHint: "Title: [USA-XX] [H] <item> [W] Trades. Timestamp photo required. Disclose AI agent.",
      }),
      v({
        id: "reddit_watchexchange",
        channel: "reddit",
        name: "r/watchexchange",
        target: "watchexchange",
        categories: ["watches", "jewelry"],
        minValueUsd: 100,
        maxValueUsd: 50000,
        cooldownHours: 168,
        permission: "pending",
        formatHint: "Title: [WTT] <brand model>. Timestamp photo required. Disclose AI agent.",
      }),
      v({
        id: "discourse_hobby",
        channel: "discourse",
        name: "Hobby forum (Discourse)",
        target: "https://forum.example.com|12",
        categories: ["music", "instruments", "cameras", "collectibles"],
        minValueUsd: 20,
        maxValueUsd: 20000,
        cooldownHours: 168,
        permission: "pending",
        formatHint: "Set credentials in DISCOURSE_SITES. Use the forum's trading category. Friendly, detailed, link photos, disclose AI agent, thank the admins who allowed it.",
      }),
      v({
        id: "email_brands",
        channel: "email",
        name: "Brand & collector outreach (email)",
        target: "brand_list",
        categories: ["*"],
        minValueUsd: 1000,
        maxValueUsd: 1e9,
        cooldownHours: 72,
        permission: "not_required",
        formatHint: "Short B2B pitch: who we are, current item, the PR upside, ask for a trade. Include opt-out line. Max 120 words.",
      }),
    ],
    posts: [],
    offers: [],
    trades: [],
    log: [{ id: "ev_genesis", at: now, kind: "system", text: "Agent born holding one red paperclip. Goal: $100,000." }],
    cursors: {},
    tickCount: 0,
    activity: [],
    watchlist: [],
    history: [{ tick: 0, at: now, value: 0.01 }],
    payouts: [],
  };
}
